// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkApi.Models;

namespace CretaceousPark.Migrations
{
    [DbContext(typeof(ParkApiContext))]
    partial class ParkApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Activities = "Hiking",
                            Location = "Colorado",
                            Name = "Rockymountain",
                            Type = "NP",
                            YearFounded = 1924
                        },
                        new
                        {
                            ParkId = 2,
                            Activities = "Hiking",
                            Location = "Washington",
                            Name = "Mt.rainier",
                            Type = "NP",
                            YearFounded = 1915
                        },
                        new
                        {
                            ParkId = 3,
                            Activities = "Surfing",
                            Location = "Washington",
                            Name = "Capedisappointment",
                            Type = "SP",
                            YearFounded = 1936
                        },
                        new
                        {
                            ParkId = 4,
                            Activities = "Snowboarding",
                            Location = "Washington",
                            Name = "Mtbaker",
                            Type = "SP",
                            YearFounded = 1946
                        },
                        new
                        {
                            ParkId = 5,
                            Activities = "Kayaking",
                            Location = "Wisconsin",
                            Name = "Wyalusing",
                            Type = "SP",
                            YearFounded = 1926
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
